### ISSUE TITLE
This pip is so nice!

### ISSUE THREAD

**Issue by lan-slot** [call-report/ffiec-data-connect#2]
It is surprising that i can find this repository here!As you said:It requires a considerable amount of boilerplate code - and knowledge of esoteric terms and concepts inherent to bank regulatory data.
So i'm wondering using what code can I get data from"https://banks.data.fdic.gov/bankfind-suite/historical"?I have already have an account of FFIEC Webservice.

**Comment by mikehikes** [comment]
Thank you! Apologies for the late reply. If you have any suggestions for other features or next steps, I'll have an opportunity to update this code in the next few weeks.

To answer your question, the  FFIEC Webservice data is a near-real time feed of regulatory filings of financial data from financial institutions, while the FDIC's site is more focused on regulatory filings of structural information. FDIC data is compiled from the filings on the FFIEC webservice, but is updated at a much lower frequency.

FDIC has also not seemed to have updated its API since first introducing it, despite offering additional web site-based data sources. That, and the rate limits for FDIC are a bit stricter than webservice. But that fact is probably because fewer people know about or use webservice.
